### ISSUE TITLE
Ownership grant of org.webpieces

### ISSUE THREAD

**Issue by zreed** [gradle/plugin-portal-requests#121]
### Plugin Id
org.webpieces.templatecompiler

### Current Plugin Owner
zreed

### Expected Plugin Owner
zreed, deanhiller

### Context
deanhiller is also a contributor and we'd like to both be able to publish releases.

**Comment by jjustinic** [comment]
Plugins cannot be owned by multiple users. You need to decide which single account you want the plugin to be owned by (could be a new "organizational" account for webpieces) and update your request. You will either need to share credentials for the account that you end up using or automate the process so that your release pipeline can be run by any appropriate party without know the exact credentials.

I do not work for Gradle and cannot process this request or change how it works. Just letting you know the options.

**Comment by ljacomet** [comment]
To be complete: the underlying DB / some app logic somewhat already works with multiple owners.
However this is very partial and brittle. We would like to offer that support in the future, but there is no ETA I can share.
For now, please use a setup that requires a single owner.

**Comment by ljacomet** [comment]
Closing as this cannot be done right now
