### ISSUE TITLE
Transfer `org.embulk.embulk-plugins` from dmikurube to embulk

### ISSUE THREAD

**Issue by dmikurube** [gradle/plugin-portal-requests#154]
### Plugin Id

`org.embulk.embulk-plugins`

* Portal: https://plugins.gradle.org/plugin/org.embulk.embulk-plugins
* Repository: https://github.com/embulk/gradle-embulk-plugins

### Current Plugin Owner

`dmikurube` -- it's me at https://plugins.gradle.org/u/dmikurube authorized via GitHub.

### Expected Plugin Owner

`embulk` -- https://plugins.gradle.org/u/embulk

### Context

We wanted to manage this plugin as a team, not by myself as an individual.

**Comment by eskatos** [comment]
Do you want the [org.embulk.plugins.gradle](https://plugins.gradle.org/plugin/org.embulk.plugins.gradle) plugin to also be transferred? It looks to be the same plugin with an older ID.

**Comment by dmikurube** [comment]
Ah, that plugin has been deprecated, and no longer used. Unnecessary to transfer. Thanks!

**Comment by eskatos** [comment]
I'm asking because it shares the same namespace.
It would make it simpler to transfer it alongside the other.
Note that we don't delete past plugins as the portal is mirrored.

Do you confirm you want to keep it on your personal account? Or would it be ok to transfer it alongside the other so that the new owner is the sole manager of the `org.embulk` namespace?

**Comment by dmikurube** [comment]
Thanks, understood the point.

Then, I'm totally fine to tranfer that old one.

**Comment by eskatos** [comment]
Thanks!

Ownership transfer is done. `embulk` is now the owner of `org.embulk.plugins.gradle` and `org.embulk.embulk-plugins` plugins.

**Comment by dmikurube** [comment]
Thanks!

**Comment by dmikurube** [comment]
@eskatos Hi, I made a publish of `org.embulk.embulk-plugins` now from the new `embulk` user, but I was said like below :

> Publishing plugin org.embulk.embulk-plugins version 0.5.3
> Thank you. Your new plugin org.embulk.embulk-plugins has been submitted for approval by Gradle engineers. The request should be processed within the next few days, at which point you will be contacted via email.
>
> https://github.com/embulk/gradle-embulk-plugins/runs/7424524923?check_suite_focus=true

* Is it just because it's the first release from the user `embulk`?
* Once it's approved by Gradle engineers, will it override https://plugins.gradle.org/plugin/org.embulk.embulk-plugins properly?
* Wouldn't next releases from `embulk` be blocked like this?

**Comment by eskatos** [comment]
Hi,

I received your submission. It has been flagged for review because of a change in the JAR coordinates. It doesn't affect the plugin ID and, yes, it will override https://plugins.gradle.org/plugin/org.embulk.embulk-plugins. Once approved you'll be able to publish new versions without approval.

You should have received an email asking to confirm the JAR coordinates change.

**Comment by dmikurube** [comment]
Got it. Thanks!
