### ISSUE TITLE
Remove io.github.propactive v1.0.0 and v1.0.1

### ISSUE THREAD

**Issue by u-ways** [gradle/plugin-portal-requests#160]
### Plugin Id

[io.github.propactive](https://plugins.gradle.org/plugin/io.github.propactive)

Versions to delete:
- "v1.0.0": io.github.propactive:propactive-plugin:v1.0.0
- "v1.0.1": io.github.propactive:propactive-plugin:v1.0.1

### Current Plugin Owner

I am the plugin owner:
u-ways ([ue95.career@gmail.com](mailto:ue95.career@gmail.com))

### Context

I am removing the "v" prefix to my sem-versioning (i.e. same versions will be released without the "v" prefix)

**Comment by ljacomet** [comment]
We do not delete plugins unless there is a serious issue with them, like intellectual property issue or similar.
Doing otherwise would break the "write once" model of artifact repositories.

And since the `1.0.0` version already published is ranked higher than the `v*` versions, there is not even a version ordering issue.

What we can help with is update the description of the `v*` version with a text you provide to indicate this change in versioning strategy.

**Comment by u-ways** [comment]
Hello, 

I see, that's okay, I thought since no one is using those versions as of current, it would be harmless to delete them. Can you add the description: 

For 1.0.0:
- "Versioning strategy prefixed with `v` is deprecated, please use the non-prefixed version (i.e. 1.0.0)"

For 1.0.1:
- "Versioning strategy prefixed with `v` is deprecated, please use the non-prefixed version (i.e. 1.0.1)"

**Comment by u-ways** [comment]
Hello @ljacomet , any updates on the progress of this please?

**Comment by jbartok** [comment]
Looking into it today.
