### ISSUE TITLE
Gradle Plugin Portal doesn't keep DSL choice after page reload

### ISSUE THREAD

**Issue by gildor** [gradle/plugin-portal-requests#210]
New DSL switcher on Gradle Plugin Portal doesn't keep user's choice about DSL.
But for example, Gradle docs support this and remember preferred DSL language

1. Open a page of any plugin on Gradle Plugin Portal, for example this one:
https://plugins.gradle.org/plugin/com.github.johnrengelman.plugin-shadow
2. Select "Kotlin" tab to switch DSL language
3. Reload page or open any other plugins' page

### Expected Behavior
"Kotlin" tab should be active, Kotlin DSL snippet should be visible

### Current Behavior
"Groovy" tab will be active

**Comment by ov7a** [comment]
We decided that it does not make much sense to keep showing different syntax for this simple operation.

Since it's a shortcut (and does not work in all cases), we decided it would be more straightforward to just leave the option that works both for Kotlin and Groovy syntax:

![Image](https://github.com/user-attachments/assets/4ff5d94f-7079-40fb-ad97-9ce0bf54f483)

This makes this issue obsolete.
