### ISSUE TITLE
Removal: NewRelic Android Agent plugin

### ISSUE THREAD

**Issue by cthomas-newrelic** [gradle/plugin-portal-requests#228]
The plugin staged earlier this year was POC and caused an unintended security violation. I'd like to start over with a fresh slate and plugin ID.

### Plugin Id
com.newrelic.agent.android

### Current Plugin Owner
mobile-agents@newrelic.com

### Context
https://github.com/newrelic/newrelic-android-agent
https://github.com/cthomas-newrelic

**Comment by ov7a** [comment]
Hello! Usually, we don't remove plugins since that can break user builds. Your plugin had more than 1000 downloads for the past six months. Please share the details of the security violation with us via email to justify the removal of the plugin _version_. And I think an update should be released first so the affected users have some replacements.

**Comment by cthomas-newrelic** [comment]
Thank you for the response, @ov7a . The plugin contained on GPP is is a snapshot of the agent's first 7.0 major version  release (we are currently at 7.5). It doesn't match what is deployed on MavenCentral, and the plugin name is incorrect. I will email details of the security issue.

**Comment by ov7a** [comment]
FTR, the conversation was continued via e-mail.

Closing since the e-mail thread wasn't updated for two weeks.
