### ISSUE TITLE
please delete the 4 plugins in group (gradle.plugin.)io.github.dexpatcher.dexpatcher-gradle

### ISSUE THREAD

**Issue by Lanchon2** [gradle/plugin-portal-requests#53]
hi,

please delete these plugins published by me:

### Plugin Ids

version 2.1.0 of:

- io.github.dexpatcher.apk-library
- io.github.dexpatcher.base
- io.github.dexpatcher.patch-library
- io.github.dexpatcher.patched-application

### Current Plugin Owner

@Lanchon and @Lanchon2

### Context

- i expected a window of 7 days to delete the plugins, but i had zero chance because your system erroneously counts live time since submission instead of approval:
  - before approval, i could not delete the plugins because of [this issue](https://github.com/gradle/plugin-portal-requests/issues/50) i filed earlier.
  - right after the plugins were approved, i still could not delete them because you took more than 7 days to approve them and the system erroneously said they were published over a week ago.

- i followed the docs on how to avoid the `gradle.plugin.` prefix, but still your system added that prefix, which is unacceptable for my application.

- i found out (late, because of lack of proper documentation) that the portal publish plugin is closed source proprietary software. i will not knowingly use proprietary software so i decided against publishing my new plugins in the portal. they are already published elsewhere (and under the correct artifact group). these copies will only cause confusion for users.

### More Information

- i waited over a week for the plugins to be approved so i could delete them, only to find out that the system malfunctioned and i could not delete them.

- i was banned from the gradle github org for complaining about the lack of visibility of the fact that the plugin portal publish plugin is closed-source proprietary software a few days before the approval, so i could not file a github support issue here.

- but instead i used [this contact form](https://plugins.gradle.org/docs/get-help) to request the deletion of the plugins only 2 hours after they were published, but you never acted on or replied to my email.

- so i had to create this silly @Lanchon2 account just to be able to file this issue here.

thanks,
Lanchon

**Comment by Lanchon2** [comment]
proof that @Lanchon and @Lanchon2 are the same person:
https://gist.github.com/Lanchon/d9a0a0253d722206c92fa9f3acf69094

**Comment by Lanchon2** [comment]
hey @big-guy,

i've been waiting for ALMOST A YEAR for a response to this issue or a response to my contact via your contact form.

i need help before your systems failed:
- they changed the package name even though i followed your published instructions on how to avoid that.
- they did not allow deletion at any time even thought your website promises a 7-day window for deletion.

is anybody handling plugin portal issues at all?

thank you very much

**Comment by ov7a** [comment]
Hello! Sorry for the late reply. This repository was out of our team's attention for a while.

Your plugins were deleted.

We're sorry you have experienced these issues. Indeed, there is room for us to improve.
* I've created a separate [issue](https://github.com/gradle/plugin-portal-requests/issues/187) for incorrect removal window calculation (right now it's 7 days from plugin creation time, but should be from approval time).
* `gradle.plugin` prefix issue might be caused by an old version of publish plugin.
* The issue of closed source has been discussed already [here](https://github.com/gradle/gradle/issues/13544).

Note that your previous account was [banned for repeated violations](https://github.com/gradle/gradle/issues/13544#issuecomment-651178701) of our code of conduct.
