### ISSUE TITLE
Provide guidance to plugin authors relying on Bintray sync

### ISSUE THREAD

**Issue by lacasseio** [gradle/plugin-portal-requests#78]
### Expected Behavior

Ensure a stable plugin release process for plugin authors using Bintray sync.

### Current Behavior

Since the JFrog announcement on February 3rd on sunsetting Bintray there hasn't been any information on what is going to happen to the plugins hosted on Bintray.

### Context

JFrog announcement: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### Steps to Reproduce 

- 28th of February will prevent any users from publishing new versions
- 1st of May the plugins will disappear together with Bintray

**Comment by tbroyer** [comment]
Fwiw, JCenter will actually become **read-only** on May 1st, until Feb 1st 2022 where it will then disappear. It's not absolutely clear whether it'll provide new versions deployed to Central or really be frozen; when they write “Only the JCenter REST API and UI will be sunsetted on May 1st 2021.” I suppose it means that it'll continue to proxy Central and will then provide new versions and artifacts published there after May 1st, rather than being completely frozen.

**Comment by lacasseio** [comment]
You are right, but I'm not going to stop releasing plugins starting on May 1st :-) What is the guideline and recommendation for plugins author that were using the Bintray repository as a more relaxed way to publish their plugins? I agree that we should all sign artifacts and have a complete POM but what about migrating older plugin versions, etc.

**Comment by big-guy** [comment]
If you can, please reclaim your plugins and try publishing to the plugin portal directly.

We're going to make sure any plugins that are already available on the portal today will still be available after the Bintray API shutdown at the end of March.

https://blog.gradle.org/jcenter-shutdown

I agree that the communication around what exactly happens after May has been unclear. We're going with the assumption that JCenter will continue to mirror Maven Central until February 2022, but we'll be working to make sure we're not completely dependent on JCenter before then.
