### ISSUE TITLE
Failed Bintray sync left invalid version metadata

### ISSUE THREAD

**Issue by ben-manes** [gradle/plugin-portal-requests#84]
I attempted to release a plugin version, 0.37.0, using the original Bintray portal sync flow. This was published to Bintray but the portal sync did not occur, [leaving](https://plugins.gradle.org/plugin/com.github.ben-manes.versions) it at the older 0.36.0 release. This was to accept a PR prior to finding the time to migrate to the new process.

I then looked into how to migrate and reclaimed the plugin (as it was setup by a contributor many years ago). I assumed that the plugin sync process had been disabled due to bintray's deprecation.

I followed the publishing instructions, removed bintray, and attempted to release the current version to the portal. I received the following error:

```
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.github.ben-manes.versions', version: '0.37.0' exists already. It was created: 2021-02-23 04:08:49.119

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Why does 0.37.0 exist but not available to users on the portal? Should I create a 0.38.0 version to resolve this gap?

**Comment by big-guy** [comment]
We're still syncing from Bintray until the end of March.

It looks like 0.37.0 is missing metadata on the Bintray side: 
https://bintray.com/fooberger/maven/com.github.ben-manes%3Agradle-versions-plugin/0.37.0#files/com%2Fgithub%2Fben-manes%2Fgradle-versions-plugin%2F0.37.0

So the sync process knows that the version is there and won't let the direct publishing process overwrite it, but since it's missing metadata, it won't show up as an available version on the portal.

I think you could either...
1. Delete and republish 0.37.0 on Bintray (I think this would resync)
2. Skip to 0.38.0 and publish directly to the plugin portal
3. Delete 0.37.0 on Bintray and publish it to the plugin portal

You won't be able to publish 0.37.0 directly to the portal as long as it looks like there's a version that should come from Bintray.

**Comment by ben-manes** [comment]
Thanks! When we upgraded from TravisCI to Github Actions due to its turndown, we switched from the old maven plugin to bintray's. Somehow that must have not pushed the pom, and we didn't need to release until I tried to sneak one in before the bintray migration was required. I'll release 0.38 as the simplest, I just totally missed that the publishing borked itself.
