### ISSUE TITLE
Change the face of the Vaadin plugin to something else (or nothing)

### ISSUE THREAD

**Issue by mstahv** [gradle/plugin-portal-requests#92]
### Plugin Id

https://plugins.gradle.org/plugin/com.vaadin

### Current Plugin Owner

Vaadin, but there is my email used for the account and my face on the plugin 😂

### Expected Plugin Owner

Vaadin, but if we can change the email to flow.team at vaadin.com, maybe the photo of the bold dude would disappear. I and the development team is reading that email, so it should be a valid contact as well.

### Context

All would be fine if there was a feature to define the photo/logo, instead of the system pulling it up from some undefined location 😉

**Comment by ljacomet** [comment]
When the user is a GitHub user, that avatar will be used. Otherwise Gravatar is used based on the user email.
And currently that email is yours, and thus the picture is yours 😉 

Updating the email of the user is possible. With the one given above, a default gravatar will be retrieved.

Please confirm if you want the user email to be updated.

**Comment by mstahv** [comment]
That would be great first step Louis!

Just created a "Gravatar account" for that email, hopefully we get a nice Vaadin logo for it now.

**Comment by ljacomet** [comment]
Done
